language: cpp
compiler: gcc
dist: xenial

env:
  - CODECOV_TOKEN="d330997c-36e9-4a4a-bf7f-0a5fb83fd603"

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - g++ -march=knl -Wall -std=c++11 -o regtest simple10avx.cpp regtest.cpp
  #- ./code_coverage.sh
  
after_success:
  #- bash <(curl -s https://codecov.io/bash)
