language: cpp
compiler: gcc
dist: trusty


env:
  #- CODECOV_TOKEN="3aec67ed-b8ba-4418-b5c4-e63b2b86d6b5"

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - g++ -Wall -march=native -o regtest simple10avx.cpp regtest.cpp
  #- ./code_coverage.sh
  
after_success:
  #- bash <(curl -s https://codecov.io/bash)
